[package]
name = "gnina_extract_affinities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.20"
itertools = "0.10.3"
polars = { version = "0.23.2", features = ["parquet"] }
